const express = require("express");
const router = require("./routes");
const { join } = require("path");
require("dotenv").config();
const app = express();
app.set("port", process.env.PORT || 3000);
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(express.static(join(__dirname, "..", "public")));
app.use(router);
module.exports = app;
